version: '3.8'
services:
  mc-smoe:
    image: wazenmai/mc-smoe:latest
    build:
      context: .
    container_name: mc-smoe
    volumes:
      - /home/ubuntu/warehouse/huggingface:/app/warehouse/huggingface
      - /home/ubuntu/warehouse/results:/app/results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      HF_HOME: "/app/warehouse/huggingface"
      NCCL_P2P_DISABLE: "1"
      TOKENIZERS_PARALLELISM: "false"
    command:
      - bash
      - scripts/mixtral/freq-merge.sh
      
          